// reflections.js
export const reflections = [
  {
    id: '1',
    userName: 'Anjali Sharma',
    profilePicUrl: 'https://example.com/profiles/anjali.jpg',
    title: 'आज की ध्यान अनुभूति',
    content: 'ध्यान में गहराई से उतरने का अनुभव मिला, अब तक का सबसे शांत समय था।',
    mediaType: 'image',
    mediaUrl: 'https://via.placeholder.com/300x200.png?text=Meditation+Image',
    isAnonymous: false,
    createdAt: '2025-05-16T04:30:00Z',
    likes: 24,
    comments: 3,
  },
  {
    id: '2',
    userName: null,
    profilePicUrl: null,
    title: 'मन की स्थिरता',
    content: 'मंत्र जप के बाद मन में एक सन्नाटा सा छा गया। बहुत गहरा अनुभव था।',
    mediaType: 'audio',
    mediaUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    isAnonymous: true,
    createdAt: '2025-05-15T10:00:00Z',
    likes: 12,
    comments: 1,
  },
  {
    id: '3',
    userName: 'Rahul Verma',
    profilePicUrl: 'https://example.com/profiles/rahul.jpg',
    title: 'Video Reflection',
    content: 'आज के ध्यान सत्र के बाद जो भावनाएँ आईं, वो इस वीडियो में साझा कर रहा हूँ।',
    mediaType: 'video',
    mediaUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isAnonymous: false,
    createdAt: '2025-05-14T07:15:00Z',
    likes: 30,
    comments: 7,
  },
];
